import React,{useState,useRef,useEffect} from 'react';
import {Armchair,ArrowUpRight,ArrowUp,ArrowDown,RotateCcw,MoveUpRight,Play,Pause,LockKeyhole,Unlock,Layers,Check,ChevronRight,MousePointer2} from 'lucide-react';
import {createChair} from './scene.js';
import {initialConfig,finishes,parts,createMotion,liftStatus} from './model.js';
import {fabricSampleUrl} from './fabric-data.js';
import {viewSelection,assemblySteps} from './inspection.js';
import {enterRide} from './ride.js';
import '@fontsource/space-grotesk/400.css';
import '@fontsource/space-grotesk/500.css';
import '@fontsource/space-grotesk/700.css';

function Range({label,value,min,max,unit='',onChange,disabled=false}){return <label className="range"><span>{label}<b>{value}<small>{unit}</small></b></span><input aria-label={label} type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)} disabled={disabled}/></label>;}
const stageLabels={ready:'自由探索',raise:'01 / 空载升高',lower:'02 / 承重下降',recline:'03 / 靠背后仰',swivel:'04 / 椅身旋转'};

export function App(){
  const [weave]=useState(fabricSampleUrl);
  const [config,setConfig]=useState(initialConfig),[motion,setMotion]=useState(createMotion),[tab,setTab]=useState('adjust'),[error,setError]=useState(''),[ready,setReady]=useState(false);
  const host=useRef(null),studio=useRef(null),select=useRef(null),content=useRef(null);
  const patch=values=>setConfig(c=>({...c,...values}));
  const chooseView=view=>{if(config.rideEnabled)setTab('adjust');setConfig(c=>viewSelection(c,view));};
  const changeTab=id=>{setTab(id);setConfig(c=>id==='ride'?enterRide(c):{...c,inspect:id==='structure',rideEnabled:false,ridePlaying:false});};
  const setExplosion=explode=>setConfig(c=>({...viewSelection(c,'full'),explode,inspect:true}));
  const assemble=()=>setConfig(c=>({...viewSelection(c,'full'),explode:0}));
  select.current=id=>{setTab('structure');setConfig(c=>({...viewSelection(c,id),inspect:true}));};
  useEffect(()=>{try{studio.current=createChair(host.current,setMotion,id=>select.current(id));studio.current.update(initialConfig);setReady(true);}catch(e){setError('三维画面未能启动，请在支持 WebGL 的浏览器中打开。');console.error(e);}return()=>studio.current?.dispose();},[]);
  useEffect(()=>studio.current?.update(config),[config]);
  useEffect(()=>{if(content.current)content.current.scrollTop=0;},[tab,config.selectedPart]);
  const selected=parts.find(p=>p.id===config.selectedPart),height=Math.round(motion.height),displayLoaded=config.demo?motion.loaded:config.loaded,displayLocked=config.demo?motion.locked:config.tiltLocked;
  const blocked=config.demo||config.explode>0||config.rideEnabled;
  const step=assemblySteps.findLast(s=>config.explode>=s.value);
  function reset(){setConfig(c=>({...initialConfig,reset:c.reset+1}));setMotion(createMotion());setTab('adjust');}
  function tabKeys(e){const all=[...e.currentTarget.querySelectorAll('button')],i=all.indexOf(document.activeElement);let next;if(e.key==='ArrowRight')next=(i+1)%all.length;else if(e.key==='ArrowLeft')next=(i+all.length-1)%all.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=all.length-1;else return;e.preventDefault();all[next].focus();all[next].click();}
  return <div className="app" style={{'--weave':'url("'+weave+'")'}}>
    <header className="header"><a className="brand" href="../../"><span className="brand-mark"><Armchair size={23}/></span><span>FORM <b>/</b> LAB<small>INTERACTIVE OBJECTS</small></span></a><span className="header-label">012 — 升降椅交互工坊</span><button className="reset" onClick={reset} aria-label="恢复默认配置"><RotateCcw size={15}/><span>恢复默认</span></button></header>
    <main className="workspace">
      <section className="viewer" aria-label="升降椅展示区" data-detail={config.view!=='full'} data-exploded={config.explode>0} data-riding={config.rideEnabled}>
        {config.rideEnabled&&<div className="ride-caption"><span>SEATED / IN MOTION</span><b>坐着，滑一段。</b><small>人物姿态示意 · 脚轮随位移滚动</small></div>}
        {config.explode>0&&config.view==='full'&&<div className="detail-caption">装配分解 · {config.explode}%<span>点击编号查看部件</span></div>}
        {config.view!=='full'&&<div className="detail-caption">{config.view==='fabric'?'面料与缝线':config.view==='lift'?'座下升降机构':config.view==='back'?'靠背与连接结构':config.view==='base'?'脚架与脚轮':config.view==='arms'?'扶手细节':'坐垫细节'}<span>拖动旋转 · 滚轮缩放</span></div>}
        <div className="intro"><div className="eyebrow"><i/> OBJECT STUDY / 012</div><h1>坐得<span>刚好。</span></h1><p>从一个拨杆，理解一把椅子。<br/>升降、后仰与旋转，都在你的掌握中。</p></div>
        <div className="scene" ref={host} data-ready={ready}>{!ready&&<div className="loading" role={error?'alert':undefined}>{error||'正在组装你的椅子…'}</div>}</div>
        <div className="view-controls" aria-label="相机视角">{[['full','整椅'],['back','侧后'],['lift','气杆'],['fabric','面料']].map(([id,label])=><button key={id} aria-pressed={config.view===id} onClick={()=>chooseView(id)}>{label}</button>)}</div>
        <div className="height-badge"><span>当前座高</span><strong data-testid="seat-height">{height}<small>mm</small></strong><div className="height-track"><i style={{height:`${(height-430)/120*100}%`}}/></div><small>430 — 550 mm</small></div>
        <div className={`load-badge ${motion.loaded?'loaded':''}`}><i/>{motion.loaded?'模拟坐下 · 有人承重':'模拟起身 · 无人承重'}</div>
        <div className="viewer-bottom"><span className="drag-hint"><MousePointer2 size={13}/> 拖动旋转 · 滚轮缩放 · 点击部件</span>{config.rideEnabled?<button className={`demo-button ${config.ridePlaying?'active':''}`} onClick={()=>patch({ridePlaying:!config.ridePlaying})}>{config.ridePlaying?<Pause size={15}/>:<Play size={15}/>}<span>{config.ridePlaying?'暂停滑行':'开始滑行'}</span></button>:<button className={`demo-button ${config.demo?'active':''}`} aria-pressed={config.demo} onClick={()=>setConfig(c=>({...viewSelection(c,'full'),demo:!c.demo,explode:0}))}>{config.demo?<Pause size={15}/>:<Play size={15}/>}<span>{config.demo?'停止演示':'看一遍完整演示'}</span><ArrowUpRight size={15}/></button>}</div>
        {config.rideEnabled&&<div className="ride-readout"><div role="status">{config.ridePlaying?'往返滑行中':'已停稳'}</div><span>{Math.abs(motion.rideVelocity||0).toFixed(2)} m/s</span></div>}
        {config.view==='lift'&&<div className={'mechanism-status '+(displayLocked?'locked':'unlocked')} role="status"><b>{displayLocked?'后仰已锁定':'后仰已解锁'}</b><span>{displayLocked?'锁止销插入 · 保持角度':'锁止销退出 · 允许后仰'}</span></div>}{config.demo&&<div className="demo-stage" role="status">{stageLabels[motion.stage]}<small>自动循环 / 操作下方按钮可停止</small></div>}
      </section>
      <aside className="control-panel" aria-label="升降椅配置面板"><div className="panel-heading"><span>让舒适，随你而动</span><small>YOUR CHAIR, YOUR WAY</small></div>
        <div className="tabs" role="tablist" aria-label="配置分类" onKeyDown={tabKeys}>{[['adjust','调节体验'],['ride','乘坐滑行'],['finish','面料配色'],['structure','结构检视']].map(([id,label])=><button id={`tab-${id}`} key={id} role="tab" aria-selected={tab===id} aria-controls="settings" tabIndex={tab===id?0:-1} onClick={()=>changeTab(id)}>{label}</button>)}</div>
        <div className="panel-content" ref={content} role="tabpanel" id="settings" aria-labelledby={`tab-${tab}`}>
          {tab==='ride'&&<><div className="section-title"><span>01</span><h2>带上乘坐者</h2><Armchair size={18}/></div><p className="muted">人物坐稳、双脚轻抬，随椅子一起滑行。<br/>轮叉转向，轮胎跟随移动距离滚动。</p><div className="ride-summary"><span>往返范围<b>1.16 <small>m</small></b></span><span>累计滑行<b>{(motion.rideDistance||0).toFixed(1)} <small>m</small></b></span></div><div className="setting-group"><div className="section-title"><span>02</span><h2>选择滑行节奏</h2></div><div className="ride-speeds" aria-label="滑行速度">{[[.25,'舒缓'],[.4,'自然'],[.6,'轻快']].map(([speed,label])=><button key={speed} aria-pressed={config.rideSpeed===speed} onClick={()=>patch({rideSpeed:speed})}>{label}<small>最高 {speed.toFixed(2)} m/s</small></button>)}</div><p className="small-note">接近两端时减速，再向另一侧滑行。</p><button className="ride-start" onClick={()=>patch({ridePlaying:!config.ridePlaying})}>{config.ridePlaying?<Pause size={17}/>:<Play size={17}/>} {config.ridePlaying?'停下休息':'让椅子滑起来'}</button><button className="secondary" onClick={()=>patch({ridePlaying:false,rideReset:config.rideReset+1})}>回到起点 <RotateCcw size={14}/></button></div><div className="ride-note"><b>观察这些细节</b><p>人物与座椅一起移动；地面刻度保持固定；五组轮叉随方向转动，轮毂标记随轮胎旋转。</p><small>这是预设路径与姿态演示，尚未模拟蹬地、摩擦力或人体平衡。切换其他页签会退出滑行。</small></div></>}
          {tab==='adjust'&&<>{config.explode>0&&<div className="assembly-notice">分解中，收回部件后可调节机构。<button onClick={assemble}>收回分解，开始调节</button></div>}<section className="setting-group"><div className="section-title"><span>01</span><h2>气杆升降</h2><MoveUpRight size={17}/></div><p className="muted">先选择承重状态，再抬起拨杆。<br/>松开拨杆，座高就会停在当前位置。</p><div className="segmented" aria-label="承重状态"><button disabled={blocked} aria-pressed={!displayLoaded} onClick={()=>patch({loaded:false})}>起身 · 升高 <ArrowUp size={14}/></button><button disabled={blocked} aria-pressed={displayLoaded} onClick={()=>patch({loaded:true})}>坐下 · 降低 <ArrowDown size={14}/></button></div><button className={`lever-button ${motion.lever?'pressed':''}`} disabled={blocked} aria-pressed={motion.lever} onClick={()=>patch({lever:!config.lever})}><span className="lever-icon">↗</span><span>{motion.lever?'松开升降拨杆':'抬起升降拨杆'}<small>{motion.lever?'关闭阀门 · 保持高度':'打开阀门 · 开始调节'}</small></span><ChevronRight size={17}/></button><div className="status-line" data-testid="lift-status"><i className={motion.lever?'moving':''}/>{liftStatus(motion)}</div><div className="inline-link"><button onClick={()=>chooseView('lift')}>看看座下拨杆 <ArrowUpRight size={13}/></button></div></section>
            <section className="setting-group"><div className="section-title"><span>02</span><h2>后仰与支撑</h2><button className="lock-button" disabled={blocked} aria-pressed={displayLocked} onClick={()=>patch({tiltLocked:!config.tiltLocked,lockAngle:config.recline})}>{displayLocked?<LockKeyhole size={13}/>:<Unlock size={13}/>} {displayLocked?'解锁后仰':'锁定角度'}</button></div><Range label="靠背后仰" value={config.demo?Math.round(motion.recline):config.recline} min={0} max={22} unit="°" disabled={config.tiltLocked||blocked} onChange={recline=>patch({recline})}/><p className="small-note">{displayLocked?'已锁定当前角度，解锁后可调节。':'坐垫会随靠背轻微倾斜，锁定可保持角度。'}</p><div className="inline-link"><button onClick={()=>chooseView('lift')}>查看后仰锁止机构 <ArrowUpRight size={13}/></button></div><Range label="扶手升高" value={config.armHeight} min={0} max={70} unit="mm" disabled={blocked} onChange={armHeight=>patch({armHeight})}/><Range label="腰托升高" value={config.lumbar} min={0} max={50} unit="mm" disabled={blocked} onChange={lumbar=>patch({lumbar})}/></section>
            <section className="setting-group"><div className="section-title"><span>03</span><h2>转个方向</h2></div><Range label="椅身旋转" value={config.demo?Math.round(motion.swivel):config.swivel} min={0} max={360} unit="°" disabled={blocked} onChange={swivel=>patch({swivel})}/><p className="small-note">坐垫、靠背和扶手一起转动，底座保持固定。</p></section></>}
          {tab==='finish'&&<><div className="section-title"><span>01</span><h2>织物与色彩</h2></div><p className="muted">交错纱线、细微混色与柔和哑光。<br/>坐垫、靠背与扶手面同步换色。</p><button className="secondary" onClick={()=>chooseView('fabric')}>放大查看织纹与缝线 <ArrowUpRight size={14}/></button><div className="finishes">{finishes.map((f,i)=><button key={f.name} aria-pressed={config.finish===i} onClick={()=>patch({finish:i})}><span className="swatch" style={{backgroundColor:f.color}}/><span>{f.name}<small>{f.en}</small></span>{config.finish===i&&<Check size={16}/>}</button>)}</div><div className="setting-group"><div className="section-title"><span>02</span><h2>头枕配置</h2></div><button className="toggle-row" role="switch" aria-label="安装头枕" aria-checked={config.headrest} onClick={()=>patch({headrest:!config.headrest})}><span>可拆卸头枕<small>与靠背同步后仰</small></span><span className="switch-track"><i/></span></button></div><div className="material-note"><span className="fabric-icon" style={{backgroundColor:finishes[config.finish].color}}/><div><b>{finishes[config.finish].name} · 混色织物</b><p>坐垫、靠背、头枕、腰托及扶手统一使用。色样为放大织纹，实际观感随光线变化。</p></div></div></>}
          {tab==='structure'&&<><div className="section-title"><span>01</span><h2>看见装配关系</h2><Layers size={17}/></div><Range label="结构分解" value={config.explode} min={0} max={100} unit="%" onChange={setExplosion}/><div className="assembly-steps" aria-label="分步查看装配">{assemblySteps.map((s,i)=><button key={s.value} aria-pressed={step.value===s.value} onClick={()=>setExplosion(s.value)}><b>{i+1}</b>{s.name}</button>)}</div><p className="step-description" role="status">{step.text}</p><div className="part-list">{parts.map((p,i)=><button key={p.id} aria-pressed={p.id===config.selectedPart} onClick={()=>select.current(p.id)}><span>0{i+1}</span>{p.name}<ArrowUpRight size={14}/></button>)}</div><article className="part-note"><small>{selected?.en||'ASSEMBLY'} / DETAIL</small><h3>{selected?.name||'整体装配'}</h3><p>{selected?.description||'选择图中编号或下方部件，查看对应位置和连接说明。'}</p></article><button className="secondary" onClick={assemble}>回到完整装配 <RotateCcw size={14}/></button><p className="small-note">展开路径用于讲解装配关系，不代表真实维修步骤。分解时暂停机构调节。</p></>}
        </div><div className="panel-footer"><i/> 实时三维 · 本地运行 <span>REACT + THREE.JS</span></div>
      </aside>
    </main>
    <footer className="page-footer"><span>FORM / LAB <b>·</b> 一次关于结构与交互的探索 · <a href="guide.html">3D 实现参考 ↗</a></span><span>尺寸与气杆行为为教学示意，无气压、载荷或人体工学仿真。</span></footer>
  </div>;
}
